### ISSUE TITLE
servercheck: ability to connect via TCP instead of socket

### ISSUE THREAD

**Issue by pataquets** [tanji/mariadb-tools#11]
Although socket sounds the most natural and optimal way of connecting, adding TCP would add flexibility and enable a few other usage scenarios, such as non-local and/or containerized deployments.

Questions:
* Is such feature supported? (I've looked at the code, but found nothing)
* Is there interest in it? Would you have time/bandwith/need on coding it?
* Would a suitable PR be accepted? (I'm not very deep in Go, but looks like a low hanging fruit and I might take a stab at it)
* Which command-line switch name would be appropiate?

**Comment by tanji** [comment]
It will take a few minutes for me to add it, I just didn't do it because I rarely use TCP on same machines, but as you said, it can help for container on non-local! I'll keep you posted!

**Comment by pataquets** [comment]
Works like a charm, thanks!
