### ISSUE TITLE
Add a real debug option for mariadb-repmgr

### ISSUE THREAD

**Issue by cpeintre** [tanji/mariadb-tools#3]
The verbose option is not enough IMO.
Thx

**Comment by tanji** [comment]
Hello Cédric,

What kind of additional debug output would you like to see?

**Comment by cpeintre** [comment]
For example, for this kind of error: WARNING: Slave srv-01:3306 not in sync. Skipping
I can't really know what is not in sync, I have to read the code to know what is expected.
Thx

**Comment by tanji** [comment]
Debug should be widely improved since latest release, I am closing this issue.
