### ISSUE TITLE
[BUG] Switch over with mariadb-repmgr generates an inconsistent state for GTID

### ISSUE THREAD

**Issue by cpeintre** [tanji/mariadb-tools#5]
**Original state:**

```
Master Host   Port      Binlog Position  Strict Mode
srv-01         3306      1-180533630-102          OFF

 Slave Host   Port  Binlog   Using GTID           Slave GTID   Replication Health  Delay  RO
  srv-02      3306      ON    Slave_Pos      1-180533630-102           Running OK      0  ON
  srv-03      3306      ON  Current_Pos      1-180533630-102           Running OK      0  ON
  srv-04      3306      ON    Slave_Pos      1-180533630-102           Running OK      0  ON
  srv-05      3306      ON  Current_Pos      1-180533630-102           Running OK      0  ON
```

**Then, perform a switch over:**

```
Master Host   Port      Binlog Position  Strict Mode
srv-05          3306      1-180533626-101          OFF

 Slave Host   Port  Binlog   Using GTID           Slave GTID   Replication Health  Delay  RO
  srv-02      3306      ON    Slave_Pos      1-180533630-102           Running OK      0  ON
  srv-03      3306      ON  Current_Pos      1-180533630-102           Running OK      0  ON
  srv-04      3306      ON    Slave_Pos      1-180533630-102           Running OK      0  ON
  srv-01      3306      ON  Current_Pos      1-180533626-101           Running OK      0  ON
```

GTID is not equal between master and slaves.
A new switch over triggers errors:

2015/01/29 14:36:54 Electing a new master
2015/01/29 14:36:54 Processing %s candidates 4
2015/01/29 14:36:54 Connecting to slave srv-02:3306
2015/01/29 14:36:54 WARNING: Slave srv-02:3306 not in sync. Skipping
2015/01/29 14:36:54 Connecting to slave srv-02:3306
2015/01/29 14:36:54 WARNING: Slave srv-02:3306 not in sync. Skipping
2015/01/29 14:36:54 Connecting to slave srv-02:3306
2015/01/29 14:36:54 WARNING: Slave srv-02:3306 not in sync. Skipping
2015/01/29 14:36:54 Connecting to slave srv-02:3306
2015/01/29 14:36:54 WARNING: Slave srv-02:3306 not in sync. Skipping
2015/01/29 14:36:54 ERROR: No suitable candidates found.

**New transaction needed on master to retrieve a correct state:**

```
Master Host   Port      Binlog Position  Strict Mode
srv-05         3306      1-180533626-103          OFF

 Slave Host   Port  Binlog   Using GTID           Slave GTID   Replication Health  Delay  RO
  srv-02      3306      ON    Slave_Pos      1-180533626-103           Running OK      0  ON
  srv-03      3306      ON  Current_Pos      1-180533626-103           Running OK      0  ON
  srv-04      3306      ON    Slave_Pos      1-180533626-103           Running OK      0  ON
  srv-01      3306      ON  Current_Pos      1-180533626-103           Running OK      0  ON
```

**Comment by tanji** [comment]
Hi Cédric,

Which repmgr version are you running? I have made some bug fixes and would like to know if this behavior was before or after those changes. Please let me know. Thanks (also retry with the latest version from source, if you can)

**Comment by cpeintre** [comment]
mariadb-repmgr --version
MariaDB Tools version 0.0.1

**Comment by tanji** [comment]
Don't believe the version string, it has not been updated in a while :) Did you download it from the releases or compile it from source?

**Comment by cpeintre** [comment]
Héhé, ok ;-)
I downloaded the binaries from the releases section.

**Comment by tanji** [comment]
Please try this one

https://github.com/tanji/mariadb-tools/releases/download/0.2.0/mariadb-repmgr

**Comment by cpeintre** [comment]
Thanks, same issue.

**Comment by tanji** [comment]
It seems that you are using different domain IDs on that topology:
180533626 on srv-01
180533630 on the others

So I think that's a matter of supporting different domains in the same replication topology.

**Comment by cpeintre** [comment]
Hum, this is not domain ID here but server ID.

**Comment by tanji** [comment]
You're correct, I was mistaken. Thanks for the information, I think I have a possible solution and will let you know.

**Comment by tanji** [comment]
Cédric,

is there a chance that you're using -gtidcheck=true?

**Comment by cpeintre** [comment]
Yes

**Comment by tanji** [comment]
OK. It does not work in its current form because it's checking slave current GTID pos vs. master binlog GTID. If nothing has been written to the master, master binlog GTID is not updated and reflects an older state. I will patch so both slave and master use current GTID pos.

**Comment by cpeintre** [comment]
Understood. Thanks
