### ISSUE TITLE
Need a way to specify MASTER_CONNECT_RETRY on mariadb-repmgr

### ISSUE THREAD

**Issue by hugochinchilla** [tanji/mariadb-tools#9]
When I do a swichover using mariadb-repmgr i would like to pass an option to set a value for the MASTER_CONNECT_RETRY as it is too low in the default value (10).

**Comment by tanji** [comment]
Hi Hugo,

good suggestion! I'll add this in the development branch.

**Comment by hugochinchilla** [comment]
The other day I learned about the `--init-slave` option in MariaDB which executes the content of a file every time `START SLAVE` completes.

https://mariadb.com/kb/en/mariadb/replication-and-binary-log-server-system-variables/#init_slave

This file should allow customizing every parameter without the need of adding support for all of them in mariadb-repmgr.

**Comment by tanji** [comment]
Fixed in main repo
